symfony-base:
    build: symfony/
    env_file: common.env
    labels:
        io.rancher.sidekicks: redis, mysql, data

symfony:
    extends:
        service: symfony-base
    links:
        - redis
        - mysql
    volumes_from:
        - data

resque:
    extends:
        service: symfony-base
    links:
         - redis
         - mysql
    command: bin/resque
    env_file: common.env
    environment:
        VVERBOSE: 1
        PREFIX: "$RESQUE_PREFIX"
        QUEUE: "$RESQUE_QUEUE"
        APP_INCLUDE: app/bootstrap.php.cache
    volumes_from:
        - data

resque_scheduler:
    extends:
        service: symfony-base
    links:
        - redis
        - mysql
    command: bin/resque-scheduler
    env_file: common.env
    environment:
        VVERBOSE: 1
        PREFIX: $RESQUE_PREFIX
    volumes_from:
        - data

nginx:
    build: nginx/
    ports:
        - 8001:80
    links:
        - fpm
    volumes_from:
        - data
    environment:
        APP_SERVER_NAME: dev-machine
    labels:
        io.rancher.sidekicks: fpm, data

fpm:
    build: php-fpm/
    links:
        - redis
        - mysql
    volumes_from:
        - data
    env_file: common.env
    environment:
        APP_SERVER_NAME: dev-machine
    labels:
        io.rancher.sidekicks: data, redis, mysql

data:
    build: data/
    volumes:
        - ./symfony/code:/var/www
        - /var/www/app/cache
        - /var/www/app/logs

redis:
    image: redis:3

mysql:
    image: mysql:5
    env_file: common.env
    environment:
        MYSQL_ROOT_PASSWORD: 8F66mppB8p1xt2M
